#!/bin/bash

# 12-combinations
cat <<'EOF' > 12-combinations
#!/bin/bash
printf "%s\n" {a..z}{a..z}|grep -v oo
EOF

# 13-print_float
cat <<'EOF' > 13-print_float
#!/bin/bash
printf "%.2f\n" $NUM
EOF

# 14-decimal_to_hexadecimal
cat <<'EOF' > 14-decimal_to_hexadecimal
#!/bin/bash
printf "%x\n" $DECIMAL
EOF

# 15-rot13
cat <<'EOF' > 15-rot13
#!/bin/bash
tr 'A-Za-z' 'N-ZA-Mn-za-m'
EOF

# 16-odd
cat <<'EOF' > 16-odd
#!/bin/bash
sed -n '1~2p'
EOF

# 17-water_and_stir
cat <<'EOF' > 17-water_and_stir
#!/bin/bash
echo $((5#$(echo $WATER|tr water 01234)+5#$(echo $STIR|tr 'stir.' 01234)))|tr 01234567 shtbeolhc
EOF
