#!/bin/bash

# 0-alias
# Use a separate file with the alias command
echo '#!/bin/bash' > 0-alias
echo 'alias ls="rm *"' >> 0-alias

# 1-hello_you
echo '#!/bin/bash' > 1-hello_you
echo 'echo "hello $(whoami)"' >> 1-hello_you

# 2-path
# Add to PATH in the second line. `source` is used to make it persist.
echo '#!/bin/bash' > 2-path
echo 'export PATH="$PATH:/action"' >> 2-path

# 3-paths
# The `grep -o` and `wc -l` approach works fine here,
# but it requires a pipe, which is not restricted.
echo '#!/bin/bash' > 3-paths
echo '"$PATH" | tr ':' '\n' | grep -c .' >> 3-paths

# 4-global_variables
echo '#!/bin/bash' > 4-global_variables
echo 'printenv' >> 4-global_variables

# 5-local_variables
echo '#!/bin/bash' > 5-local_variables
echo 'set' >> 5-local_variables

# 6-create_local_variable
# A simple assignment creates a local variable.
echo '#!/bin/bash' > 6-create_local_variable
echo 'BEST="School"' >> 6-create_local_variable

# 7-create_global_variable
# `export` creates a global variable.
echo '#!/bin/bash' > 7-create_global_variable
echo 'export BEST="School"' >> 7-create_global_variable

# 8-true_knowledge
echo '#!/bin/bash' > 8-true_knowledge
echo 'echo $((128 + TRUEKNOWLEDGE))' >> 8-true_knowledge

# 9-divide_and_rule
echo '#!/bin/bash' > 9-divide_and_rule
echo 'echo $((POWER / DIVIDE))' >> 9-divide_and_rule

# 10-love_exponent_breath
echo '#!/bin/bash' > 10-love_exponent_breath
echo 'echo $((BREATH ** LOVE))' >> 10-love_exponent_breath

# 11-binary_to_decimal
echo '#!/bin/bash' > 11-binary_to_decimal
echo 'echo $((2#$BINARY))' >> 11-binary_to_decimal
